[package]
name = "suix"
version.workspace = true
edition.workspace = true

[dependencies]
clap = { workspace = true, features = ["derive"] }
color-eyre.workspace = true
eyre.workspace = true
grpc.workspace = true
rpc.workspace = true
tokio = { workspace = true, features = ["full"] }
vanity.workspace = true
