[package]
name = "suix"
version.workspace = true
edition.workspace = true

[dependencies]
clap = { workspace = true }
color-eyre = { workspace = true }
eyre = { workspace = true }
rpc = { workspace = true }
tokio = { workspace = true }
vanity = { workspace = true }
